sudo: required
service:
    - docker

before_install:
    - docker build -t notagiant93/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true notagiant93/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-458897686757"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
